#ifndef INSTRUMENT_VERBOSE_INIT_AND_SHUTDOWN_HPP
#define INSTRUMENT_VERBOSE_INIT_AND_SHUTDOWN_HPP


#include "../api/InstrumentInitAndShutdown.hpp"


#endif // INSTRUMENT_VERBOSE_INIT_AND_SHUTDOWN_HPP
