#ifndef DATA_ACCESS_TYPE_HPP
#define DATA_ACCESS_TYPE_HPP


typedef enum {
	READ_ACCESS_TYPE,
	WRITE_ACCESS_TYPE,
	READWRITE_ACCESS_TYPE,
	CONCURRENT_ACCESS_TYPE,
	REDUCTION_ACCESS_TYPE
} DataAccessType;


#endif // DATA_ACCESS_TYPE_HPP
