#ifndef NO_HARDWARE_COUNTERS_THREAD_LOCAL_DATA_HPP
#define NO_HARDWARE_COUNTERS_THREAD_LOCAL_DATA_HPP


struct HardwareCountersThreadLocalData {
};


#endif // NO_HARDWARE_COUNTERS_THREAD_LOCAL_DATA_HPP
